language: node_js
node_js:
  - '5'
sudo: false
script:
  - npm install
  - npm test
branches:
  only:
    - master
    - /^\d+\.\d+/
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: q7e4haV9hAHng28w6EBnOc6ptorxjxeATW6ZocYiPk68To3IUHMt615rzyotfA5TBCcPJyeUJiqNcuUXbh+r8HmER4bJsjaGMpETPSkdvzQ1bYg2EJEvT6V/xc+sRGoj5ri/F2uH99AYnF99IugjeWvjpp5F5z370fJIMiUmXX8=
  on:
    tags: true
